TITLE = 'Flappy Bird Ai'

GAME_SPEED = 3
GROUND_HEIGHT = 60

# FONTS
FONT_SIZE = 18

# BUTTON SETTINGS
BUTTON_FONT = 'fonts/VictorMono-Regular.ttf'
BUTTON_FRAME_WIDTH = 1.8

# DISPLAY INFORMATIONS
FPS = 60

WIDTH = 480
HEIGHT = 640
SIZE = (WIDTH, HEIGHT)

WIDTH_CENTER = WIDTH // 2
HEIGHT_CENTER = HEIGHT // 2
CENTER = (WIDTH_CENTER, HEIGHT_CENTER)

TOP = 0
BOTTOM = HEIGHT
RIGHT = WIDTH
LEFT = 0

TOP_LEFT = (LEFT, TOP)
TOP_CENTER = (WIDTH_CENTER, TOP)
TOP_RIGHT = (RIGHT, TOP)
RIGHT_CENTER = (RIGHT, HEIGHT_CENTER)
BOTTOM_RIGHT = (RIGHT, BOTTOM)
BOTTOM_CENTER = (WIDTH_CENTER, BOTTOM)
BOTTOM_LEFT = (LEFT, BOTTOM)
LEFT_CENTER = (LEFT, HEIGHT_CENTER)

# GAME LAYERS
LAYERS = ['BACKGROUND',
          'GROUND',  # Platforms / tiles
          'OBJECTS',  # Trees bushes etc.
          'UNITS',
          'PLAYER',
          'ITEMS',
          'FOREGROUND',  # Projectiles
          'UI']  # User interface
BACKGROUND_COLOR = (33, 33, 33)

# TILES
TILE_SIZE_SMALL = (16, 16)
TILE_SIZE_MEDIUM = (32, 32)
TILE_SIZE_BIG = (64, 64)
